# Site settings
title: Sh0x
description: 'Esto es una prueba'
url: 'http://sh0x.github.io'
baseurl: ''
profilepic: '/images/pic.jpeg'
background: '/images/background.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Antonio Sanchez'
  email: shosredes@gmail.com
  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  sh0x8
  linkedin_username: sh0x
  meetup_name: 

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
